### PR TITLE
Fix small syntax errors in print statements.

### PR DESCRIPTION
**Pull request by tskisner**
Just fixing 2 syntax errors with missing parentheses in print statements.

### CODE REVIEW

**Comment by weaverba137** [comment]
If you're going to assign something to a person, can you please wait for that person to respond before merging?  Otherwise, what's the point of assigning anything to anyone?  It doesn't matter that one person made the assignment and another person closed it.

**Comment by sbailey** [comment]
ok, I unassigned you and assigned myself instead as the one who merged it so I can take any blame.  In super simple cases like this, I view the assigning as a suggestion for who might take a look, not a binding indication of who must approve it.  This case is so simple that Ted could even have self-merged it; we don't need to be super formal on adding parentheses for python 3 compatible print statements.

At the same time, I do wonder how this slipped through the cracks on previous py3 updates but I didn't track the blame history to find out whether it was newly added.  Tests, of course, would have been useful but that is a much larger issue than the py3 syntax fix.

**Comment by weaverba137** [comment]
I was legitimately interested in how this passed through the Python 3 transition process, so I'm not bringing this up just to be grumpy.

**Comment by sbailey** [comment]
Fair enough.  Our original py3 transition seemed to have missed the code in sandbox, which was later fixed in PR #7.  Those didn't impact our direct usage of redmonster but they were blocking desiInstall or sphinx or something similar.  I'm not sure how this case slipped through or whether it was a later addition.

**Pull request merged**
